import re

with open('lib/prototype_1.dart', 'r') as f:
    code = f.read()

# Replacements
replacements = [
    ("NutrixApp", "WebSimApp"),
    ("NutrixHomeScreen", "WebSimHomeScreen"),
    ("NutrixNavbar", "WebSimNavbar"),
    ("Nutrix", "WebSim"),
    ("NUTRIX", "WEBSIM"),
    ("health, understood", "web ideas, simulated"),
    ("Your health,\\nunderstood.", "Your web,\\nsimulated."),
    ("food, activity and health data", "prompts, components and design data"),
    ("Health Lens", "Web Inspector"),
    ("Search Health", "Generate Site"),
    ("Feeling Healthy", "Feeling Creative"),
    ("Health Score", "Design Score"),
    ("Health Insights", "Performance Insights"),
    ("HealthInsights", "PerformanceInsights"),
    ("QuickHealthActions", "QuickWebActions"),
    ("HealthLensScreen", "WebInspectorScreen"),
    ("FeelingHealthyScreen", "FeelingCreativeScreen"),
    ("HealthLensShowcase", "WebInspectorShowcase"),
    ("personal health intelligence", "web simulation intelligence"),
    ("Personal health intelligence", "Web simulation intelligence"),
    ("Health intelligence", "Web simulation intelligence"),
    ("food, health or fitness", "components, layout or performance"),
    ("Fitness Intelligence", "Performance Intelligence"),
    ("View Fitness", "View Performance"),
    ("Ingredient Safety", "Component Safety"),
    ("Check additives, allergens and food safety before you eat.", "Check accessibility, SEO and performance before you publish."),
    ("Check Ingredient", "Check Component"),
    ("AI Meal Creator", "AI Site Creator"),
    ("Turn your leftovers into meals that fit your nutrition goals.", "Turn your ideas into websites that fit your design goals."),
    ("Create a Meal", "Create a Site"),
    ("Scan a meal and understand calories, macros and food safety.", "Scan a component and understand HTML, CSS and accessibility."),
    ("Scan Food", "Inspect Element"),
    ("Health Score", "Design Score"),
    ("Nutrition today", "Performance today"),
    ("Protein", "LCP"),
    ("86g", "1.2s"),
    ("110g", "2.5s"),
    ("Calories", "SEO"),
    ("1,640", "92"),
    ("2,100 kcal", "100"),
    ("Activity", "Traffic"),
    ("7,420", "12,420"),
    ("Steps", "Visitors"),
    ("420", "2.4m"),
    ("kcal Burned", "Avg Duration"),
    ("Protein opportunity", "SEO opportunity"),
    ("You're about 24g below your protein target today.", "Your meta tags are missing on 2 pages."),
    ("Show Recipes", "View Pages"),
    ("Food insight", "Design insight"),
    ("Your recent meal was higher in sodium than usual.", "Your recent layout has contrast issues."),
    ("View Details", "View Details"),
    ("Movement goal", "Performance goal"),
    ("You're 1,500 steps away from today's goal.", "You're 0.4s away from your LCP goal."),
    ("Start Walking", "Optimize Code"),
    ("SEE FOOD DIFFERENTLY", "SEE WEB DIFFERENTLY"),
    ("Know what's on your plate.", "Know what's in your DOM."),
    ("Nutrix Vision recognizes food and estimates nutrition while helping you understand potential safety concerns.", "WebSim Vision recognizes components and estimates performance while helping you understand accessibility."),
    ("Food", "Component"),
    ("Recognition", "Recognition"),
    ("Nutrition", "Performance"),
    ("Estimation", "Estimation"),
    ("Safety", "Accessibility"),
    ("Analysis", "Analysis"),
    ("Try Health Lens", "Try Web Inspector"),
    ("health questions", "web development questions"),
    ("From meal planning to fitness advice", "From layout planning to performance advice"),
    ("health context", "design context"),
    ("activity today, a protein-rich dinner", "layout today, a flexbox container"),
    ("Show dinner ideas", "Show layout ideas"),
    ("Why protein?", "Why flexbox?"),
    ("Create my meal", "Create my layout"),
    ("What's on your plate?", "What's in your DOM?"),
    ("understand your meal, nutrition and food safety", "understand your layout, performance and accessibility"),
    ("Upload Image", "Upload Mockup"),
    ("Chicken Biryani", "Hero Component"),
    ("No major concerns detected", "No accessibility issues detected"),
    ("Sodium", "Contrast"),
    ("Moderate", "Good"),
    ("Allergens", "Aria Labels"),
    ("None detected", "All present"),
    ("Additives", "Console Errors"),
    ("2 detected", "0 detected"),
    ("Log to Diary", "Save Component"),
    ("Scan Again", "Inspect Again"),
    ("Blurred image", "Blurred mockup"),
    ("understand nutrition of your image", "understand the layout of your mockup"),
    ("No food", "No components"),
    ("No food items recognized", "No web components recognized"),
    ("point camera to food", "upload a valid mockup"),
    ("Poor lighting", "Low resolution"),
    ("Your environment is too dark", "Your mockup is too low resolution"),
    ("nutrition and movement", "design and performance"),
]

for old, new in replacements:
    code = code.replace(old, new)

with open('lib/prototype_web_sim.dart', 'w') as f:
    f.write(code)

